name = "shaveparlor"
compatibility_date = "2024-01-01"

pages_build_output_dir = "."

[pages]
  # Functions folder path
  functions = "functions"

[vars]
  GOOGLE_URL = "https://script.google.com/macros/s/AKfycbypSO_TIVome8l-jdIqOHjXLmfaf0Mi_8tQukNzIG9BrC8gH0sd3bcnqm4AaeSmQa7Y9A/exec"
